// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfw_wP481k53Sy9u2aqs08h62fd5pELY',
    appId: '1:860141702307:web:ea081f88f7f732e29b4316',
    messagingSenderId: '860141702307',
    projectId: 'vartmaan-pulse-app',
    authDomain: 'vartmaan-pulse-app.firebaseapp.com',
    storageBucket: 'vartmaan-pulse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VCamSPJ7ZVnDD2IUNm_JDBjYiioRi6Y',
    appId: '1:860141702307:android:1a2c6137d6322d4d9b4316',
    messagingSenderId: '860141702307',
    projectId: 'vartmaan-pulse-app',
    storageBucket: 'vartmaan-pulse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfhG9wGD_f52tTNg6zUASGDySr3gWnj0',
    appId: '1:860141702307:ios:4bcd200d6b8677f49b4316',
    messagingSenderId: '860141702307',
    projectId: 'vartmaan-pulse-app',
    storageBucket: 'vartmaan-pulse-app.firebasestorage.app',
    iosBundleId: 'com.fieldtrackpro.fieldTrackPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfhG9wGD_f52tTNg6zUASGDySr3gWnj0',
    appId: '1:860141702307:ios:4bcd200d6b8677f49b4316',
    messagingSenderId: '860141702307',
    projectId: 'vartmaan-pulse-app',
    storageBucket: 'vartmaan-pulse-app.firebasestorage.app',
    iosBundleId: 'com.fieldtrackpro.fieldTrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfw_wP481k53Sy9u2aqs08h62fd5pELY',
    appId: '1:860141702307:web:66942c5fef3222839b4316',
    messagingSenderId: '860141702307',
    projectId: 'vartmaan-pulse-app',
    authDomain: 'vartmaan-pulse-app.firebaseapp.com',
    storageBucket: 'vartmaan-pulse-app.firebasestorage.app',
  );
}
